/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsStats {
  'weeklyActiveUsers' : bigint,
  'returningLearners' : bigint,
  'currentActiveLearners' : bigint,
  'dailyActiveUsers' : bigint,
  'pageViewsToday' : bigint,
  'lessonCompletions' : bigint,
  'totalPageViews' : bigint,
  'streakCount' : bigint,
}
export interface BPLeaderboardEntry {
  'displayName' : string,
  'userId' : string,
  'rank' : bigint,
  'allTimeBP' : bigint,
}
export interface BearCredits { 'balance' : bigint, 'totalEarned' : bigint }
export interface CompleteLessonArgs {
  'lessonId' : string,
  'xpReward' : bigint,
  'worldId' : string,
}
export interface CompleteQuestArgs {
  'questDescription' : string,
  'xpReward' : bigint,
  'creditsReward' : bigint,
  'questId' : string,
}
export interface LessonProgress {
  'lessonId' : string,
  'attempted' : boolean,
  'completionTime' : Time,
  'completed' : boolean,
  'unlocked' : boolean,
}
export interface QuizAnswer {
  'isCorrect' : boolean,
  'questionId' : string,
  'selectedAnswer' : string,
}
export interface QuizResult {
  'feedback' : string,
  'score' : bigint,
  'totalQuestions' : bigint,
  'isFirstPass' : boolean,
  'passed' : boolean,
}
export interface SubmitQuizArgs {
  'lessonId' : string,
  'answers' : Array<QuizAnswer>,
}
export type Time = bigint;
export interface UpdateProfileArgs { 'displayName' : string, 'avatar' : string }
export interface UserProfile {
  'xp' : bigint,
  'lessonsCompletedToday' : bigint,
  'streak' : bigint,
  'displayName' : string,
  'lastActivityTime' : Time,
  'level' : bigint,
  'lastStreakUpdate' : Time,
  'avatar' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WinnerClaim {
  'month' : bigint,
  'displayName' : string,
  'usdcAddress' : string,
  'userId' : string,
  'year' : bigint,
  'submittedAt' : Time,
  'isPaid' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'attemptQuiz' : ActorMethod<[string], undefined>,
  'changeDisplayName' : ActorMethod<[string], string>,
  'completeLesson' : ActorMethod<
    [CompleteLessonArgs],
    {
      'bpAwarded' : bigint,
      'dailyBonusApplied' : boolean,
      'streakBonusApplied' : boolean,
      'isFirstCompletion' : boolean,
    }
  >,
  'completeOnboarding' : ActorMethod<[string, string], undefined>,
  'completeQuest' : ActorMethod<[CompleteQuestArgs], undefined>,
  'getAllWorld0Lessons' : ActorMethod<[], Array<[string, string]>>,
  'getAnalyticsStats' : ActorMethod<[], AnalyticsStats>,
  'getBearCredits' : ActorMethod<[], [] | [BearCredits]>,
  'getBestQuizScore' : ActorMethod<[string], [] | [bigint]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentWorldLessonProgress' : ActorMethod<
    [string],
    Array<LessonProgress>
  >,
  'getGlobalLeaderboard' : ActorMethod<[], Array<BPLeaderboardEntry>>,
  'getMonthlyLeaderboard' : ActorMethod<
    [bigint, bigint],
    Array<BPLeaderboardEntry>
  >,
  'getMyDailyStats' : ActorMethod<
    [],
    {
      'lessonsToday' : bigint,
      'streak' : bigint,
      'firstLessonBonusAvailable' : boolean,
    }
  >,
  'getNameChangeCount' : ActorMethod<[], bigint>,
  'getOnboardingStatus' : ActorMethod<[], [boolean, string, string]>,
  'getPersistentUserState' : ActorMethod<[], [boolean, string, string]>,
  'getPublicMetrics' : ActorMethod<
    [],
    {
      'activeLearnersToday' : bigint,
      'mostCompletedLessonWeekly' : [] | [string],
      'averageProgress' : bigint,
    }
  >,
  'getReturnedValue' : ActorMethod<[], bigint>,
  'getUserBearCredits' : ActorMethod<[Principal], [] | [BearCredits]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWorldProgress' : ActorMethod<
    [Principal, string],
    Array<LessonProgress>
  >,
  'getWinnerClaims' : ActorMethod<[], Array<WinnerClaim>>,
  'getWinnerHistory' : ActorMethod<[], Array<WinnerClaim>>,
  /**
   * / Returns true if the caller has already seen the given share milestone modal.
   */
  'hasSeenShareMilestone' : ActorMethod<[string], boolean>,
  'isAdminUser' : ActorMethod<[], boolean>,
  /**
   * / Returns true if the caller has ever submitted the boss quiz for the given world.
   * / Boss quizzes are stored in lessonAttempts under the key "boss-<worldId>".
   */
  'isBossAttempted' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isLessonUnlocked' : ActorMethod<[string], boolean>,
  /**
   * / Returns true if the caller has unlocked the given special world.
   */
  'isSpecialWorldUnlocked' : ActorMethod<[string], boolean>,
  'markClaimPaid' : ActorMethod<[bigint, bigint], undefined>,
  'markLessonAttempted' : ActorMethod<[string], undefined>,
  /**
   * / Mark the given share milestone as seen for the caller. Idempotent.
   */
  'markShareMilestoneSeen' : ActorMethod<[string], undefined>,
  /**
   * / Mark a special world as unlocked for the caller. Idempotent.
   */
  'markSpecialWorldUnlocked' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePersistentUserState' : ActorMethod<[string, string, boolean], undefined>,
  'submitBearPoints' : ActorMethod<[bigint, bigint, bigint, bigint], undefined>,
  'submitQuiz' : ActorMethod<[SubmitQuizArgs], QuizResult>,
  'submitWinnerClaim' : ActorMethod<[bigint, bigint, string], string>,
  'trackPageView' : ActorMethod<[], undefined>,
  'trackProgressEvent' : ActorMethod<[bigint], undefined>,
  /**
   * / Persists caller's current rank snapshot and returns delta vs previous snapshot.
   * / Returns null if no prior snapshot exists (first call).
   * / delta > 0 means rank improved (moved up), delta < 0 means rank dropped.
   */
  'updateMyRankSnapshot' : ActorMethod<[bigint], [] | [bigint]>,
  'updatePersistentUserState' : ActorMethod<
    [string, string, boolean],
    undefined
  >,
  'updateProfile' : ActorMethod<[UpdateProfileArgs], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];