/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CompleteLessonArgs = IDL.Record({
  'lessonId' : IDL.Text,
  'xpReward' : IDL.Nat,
  'worldId' : IDL.Text,
});
export const CompleteQuestArgs = IDL.Record({
  'questDescription' : IDL.Text,
  'xpReward' : IDL.Nat,
  'creditsReward' : IDL.Nat,
  'questId' : IDL.Text,
});
export const AnalyticsStats = IDL.Record({
  'weeklyActiveUsers' : IDL.Nat,
  'returningLearners' : IDL.Nat,
  'currentActiveLearners' : IDL.Nat,
  'dailyActiveUsers' : IDL.Nat,
  'pageViewsToday' : IDL.Nat,
  'lessonCompletions' : IDL.Nat,
  'totalPageViews' : IDL.Nat,
  'streakCount' : IDL.Nat,
});
export const AdminAnalytics = IDL.Record({
  'totalRegisteredUsers' : IDL.Nat,
  'dailyActiveUsers' : IDL.Nat,
  'monthlyActiveUsers' : IDL.Nat,
  'totalLessonCompletions' : IDL.Nat,
  'totalQuizPasses' : IDL.Nat,
  'totalBPAwarded' : IDL.Nat,
  'usersWithBP' : IDL.Nat,
});
export const BearCredits = IDL.Record({
  'balance' : IDL.Nat,
  'totalEarned' : IDL.Nat,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'lessonsCompletedToday' : IDL.Nat,
  'streak' : IDL.Nat,
  'displayName' : IDL.Text,
  'lastActivityTime' : Time,
  'level' : IDL.Nat,
  'lastStreakUpdate' : Time,
  'avatar' : IDL.Text,
});
export const LessonProgress = IDL.Record({
  'lessonId' : IDL.Text,
  'attempted' : IDL.Bool,
  'completionTime' : Time,
  'completed' : IDL.Bool,
  'unlocked' : IDL.Bool,
});
export const BPLeaderboardEntry = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : IDL.Text,
  'rank' : IDL.Nat,
  'allTimeBP' : IDL.Nat,
});
export const WinnerClaim = IDL.Record({
  'month' : IDL.Nat,
  'displayName' : IDL.Text,
  'usdcAddress' : IDL.Text,
  'userId' : IDL.Text,
  'year' : IDL.Nat,
  'submittedAt' : Time,
  'isPaid' : IDL.Bool,
});
export const QuizAnswer = IDL.Record({
  'isCorrect' : IDL.Bool,
  'questionId' : IDL.Text,
  'selectedAnswer' : IDL.Text,
});
export const SubmitQuizArgs = IDL.Record({
  'lessonId' : IDL.Text,
  'answers' : IDL.Vec(QuizAnswer),
});
export const QuizResult = IDL.Record({
  'feedback' : IDL.Text,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'isFirstPass' : IDL.Bool,
  'passed' : IDL.Bool,
});
export const UpdateProfileArgs = IDL.Record({
  'displayName' : IDL.Text,
  'avatar' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attemptQuiz' : IDL.Func([IDL.Text], [], []),
  'changeDisplayName' : IDL.Func([IDL.Text], [IDL.Text], []),
  'completeLesson' : IDL.Func(
      [CompleteLessonArgs],
      [
        IDL.Record({
          'bpAwarded' : IDL.Nat,
          'dailyBonusApplied' : IDL.Bool,
          'streakBonusApplied' : IDL.Bool,
          'isFirstCompletion' : IDL.Bool,
        }),
      ],
      [],
    ),
  'completeOnboarding' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'completeQuest' : IDL.Func([CompleteQuestArgs], [], []),
  'getAllWorld0Lessons' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAdminAnalytics' : IDL.Func([], [AdminAnalytics], ['query']),
  'getAnalyticsStats' : IDL.Func([], [AnalyticsStats], ['query']),
  'getBearCredits' : IDL.Func([], [IDL.Opt(BearCredits)], ['query']),
  'getBestQuizScore' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentWorldLessonProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LessonProgress)],
      ['query'],
    ),
  'getGlobalLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(BPLeaderboardEntry)],
      ['query'],
    ),
  'getMonthlyLeaderboard' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(BPLeaderboardEntry)],
      ['query'],
    ),
  'getMyDailyStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'lessonsToday' : IDL.Nat,
          'streak' : IDL.Nat,
          'firstLessonBonusAvailable' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getNameChangeCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getOnboardingStatus' : IDL.Func(
      [],
      [IDL.Bool, IDL.Text, IDL.Text],
      ['query'],
    ),
  'getPersistentUserState' : IDL.Func(
      [],
      [IDL.Bool, IDL.Text, IDL.Text],
      ['query'],
    ),
  'getPublicMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'activeLearnersToday' : IDL.Nat,
          'mostCompletedLessonWeekly' : IDL.Opt(IDL.Text),
          'averageProgress' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getReturnedValue' : IDL.Func([], [IDL.Nat], []),
  'getUserBearCredits' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BearCredits)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserWorldProgress' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(LessonProgress)],
      ['query'],
    ),
  'getWinnerClaims' : IDL.Func([], [IDL.Vec(WinnerClaim)], ['query']),
  'getWinnerHistory' : IDL.Func([], [IDL.Vec(WinnerClaim)], ['query']),
  'hasSeenShareMilestone' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isAdminUser' : IDL.Func([], [IDL.Bool], ['query']),
  'isBossAttempted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isLessonUnlocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isSpecialWorldUnlocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'markClaimPaid' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'markLessonAttempted' : IDL.Func([IDL.Text], [], []),
  'markShareMilestoneSeen' : IDL.Func([IDL.Text], [], []),
  'markSpecialWorldUnlocked' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePersistentUserState' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'submitBearPoints' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'submitQuiz' : IDL.Func([SubmitQuizArgs], [QuizResult], []),
  'submitWinnerClaim' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Text], []),
  'trackPageView' : IDL.Func([], [], []),
  'trackProgressEvent' : IDL.Func([IDL.Nat], [], []),
  'updateMyRankSnapshot' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Int)], []),
  'updatePersistentUserState' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateProfile' : IDL.Func([UpdateProfileArgs], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CompleteLessonArgs = IDL.Record({
    'lessonId' : IDL.Text,
    'xpReward' : IDL.Nat,
    'worldId' : IDL.Text,
  });
  const CompleteQuestArgs = IDL.Record({
    'questDescription' : IDL.Text,
    'xpReward' : IDL.Nat,
    'creditsReward' : IDL.Nat,
    'questId' : IDL.Text,
  });
  const AnalyticsStats = IDL.Record({
    'weeklyActiveUsers' : IDL.Nat,
    'returningLearners' : IDL.Nat,
    'currentActiveLearners' : IDL.Nat,
    'dailyActiveUsers' : IDL.Nat,
    'pageViewsToday' : IDL.Nat,
    'lessonCompletions' : IDL.Nat,
    'totalPageViews' : IDL.Nat,
    'streakCount' : IDL.Nat,
  });
  const BearCredits = IDL.Record({
    'balance' : IDL.Nat,
    'totalEarned' : IDL.Nat,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'lessonsCompletedToday' : IDL.Nat,
    'streak' : IDL.Nat,
    'displayName' : IDL.Text,
    'lastActivityTime' : Time,
    'level' : IDL.Nat,
    'lastStreakUpdate' : Time,
    'avatar' : IDL.Text,
  });
  const LessonProgress = IDL.Record({
    'lessonId' : IDL.Text,
    'attempted' : IDL.Bool,
    'completionTime' : Time,
    'completed' : IDL.Bool,
    'unlocked' : IDL.Bool,
  });
  const BPLeaderboardEntry = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : IDL.Text,
    'rank' : IDL.Nat,
    'allTimeBP' : IDL.Nat,
  });
  const WinnerClaim = IDL.Record({
    'month' : IDL.Nat,
    'displayName' : IDL.Text,
    'usdcAddress' : IDL.Text,
    'userId' : IDL.Text,
    'year' : IDL.Nat,
    'submittedAt' : Time,
    'isPaid' : IDL.Bool,
  });
  const QuizAnswer = IDL.Record({
    'isCorrect' : IDL.Bool,
    'questionId' : IDL.Text,
    'selectedAnswer' : IDL.Text,
  });
  const SubmitQuizArgs = IDL.Record({
    'lessonId' : IDL.Text,
    'answers' : IDL.Vec(QuizAnswer),
  });
  const QuizResult = IDL.Record({
    'feedback' : IDL.Text,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'isFirstPass' : IDL.Bool,
    'passed' : IDL.Bool,
  });
  const UpdateProfileArgs = IDL.Record({
    'displayName' : IDL.Text,
    'avatar' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attemptQuiz' : IDL.Func([IDL.Text], [], []),
    'changeDisplayName' : IDL.Func([IDL.Text], [IDL.Text], []),
    'completeLesson' : IDL.Func(
        [CompleteLessonArgs],
        [
          IDL.Record({
            'bpAwarded' : IDL.Nat,
            'dailyBonusApplied' : IDL.Bool,
            'streakBonusApplied' : IDL.Bool,
            'isFirstCompletion' : IDL.Bool,
          }),
        ],
        [],
      ),
    'completeOnboarding' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'completeQuest' : IDL.Func([CompleteQuestArgs], [], []),
    'getAllWorld0Lessons' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAdminAnalytics' : IDL.Func([], [AdminAnalytics], ['query']),
  'getAnalyticsStats' : IDL.Func([], [AnalyticsStats], ['query']),
    'getBearCredits' : IDL.Func([], [IDL.Opt(BearCredits)], ['query']),
    'getBestQuizScore' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentWorldLessonProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LessonProgress)],
        ['query'],
      ),
    'getGlobalLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(BPLeaderboardEntry)],
        ['query'],
      ),
    'getMonthlyLeaderboard' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(BPLeaderboardEntry)],
        ['query'],
      ),
    'getMyDailyStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'lessonsToday' : IDL.Nat,
            'streak' : IDL.Nat,
            'firstLessonBonusAvailable' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getNameChangeCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getOnboardingStatus' : IDL.Func(
        [],
        [IDL.Bool, IDL.Text, IDL.Text],
        ['query'],
      ),
    'getPersistentUserState' : IDL.Func(
        [],
        [IDL.Bool, IDL.Text, IDL.Text],
        ['query'],
      ),
    'getPublicMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'activeLearnersToday' : IDL.Nat,
            'mostCompletedLessonWeekly' : IDL.Opt(IDL.Text),
            'averageProgress' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getReturnedValue' : IDL.Func([], [IDL.Nat], []),
    'getUserBearCredits' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BearCredits)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserWorldProgress' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(LessonProgress)],
        ['query'],
      ),
    'getWinnerClaims' : IDL.Func([], [IDL.Vec(WinnerClaim)], ['query']),
    'getWinnerHistory' : IDL.Func([], [IDL.Vec(WinnerClaim)], ['query']),
    'hasSeenShareMilestone' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isAdminUser' : IDL.Func([], [IDL.Bool], ['query']),
    'isBossAttempted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isLessonUnlocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isSpecialWorldUnlocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'markClaimPaid' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'markLessonAttempted' : IDL.Func([IDL.Text], [], []),
    'markShareMilestoneSeen' : IDL.Func([IDL.Text], [], []),
    'markSpecialWorldUnlocked' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePersistentUserState' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'submitBearPoints' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'submitQuiz' : IDL.Func([SubmitQuizArgs], [QuizResult], []),
    'submitWinnerClaim' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'trackPageView' : IDL.Func([], [], []),
    'trackProgressEvent' : IDL.Func([IDL.Nat], [], []),
    'updateMyRankSnapshot' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Int)], []),
    'updatePersistentUserState' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateProfile' : IDL.Func([UpdateProfileArgs], [], []),
  });
};

export const init = ({ IDL }) => { return []; };