/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AnalyticsStats {
    weeklyActiveUsers: bigint;
    returningLearners: bigint;
    currentActiveLearners: bigint;
    dailyActiveUsers: bigint;
    pageViewsToday: bigint;
    lessonCompletions: bigint;
    totalPageViews: bigint;
    streakCount: bigint;
}
export interface QuizAnswer {
    isCorrect: boolean;
    questionId: string;
    selectedAnswer: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CompleteLessonArgs {
    lessonId: string;
    xpReward: bigint;
    worldId: string;
}
export interface QuizResult {
    feedback: string;
    score: bigint;
    totalQuestions: bigint;
    isFirstPass: boolean;
    passed: boolean;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface WinnerClaim {
    month: bigint;
    displayName: string;
    usdcAddress: string;
    userId: string;
    year: bigint;
    submittedAt: Time;
    isPaid: boolean;
}
export interface UpdateProfileArgs {
    displayName: string;
    avatar: string;
}
export interface BearCredits {
    balance: bigint;
    totalEarned: bigint;
}
export interface CompleteQuestArgs {
    questDescription: string;
    xpReward: bigint;
    creditsReward: bigint;
    questId: string;
}
export interface SubmitQuizArgs {
    lessonId: string;
    answers: Array<QuizAnswer>;
}
export interface BPLeaderboardEntry {
    displayName: string;
    userId: string;
    rank: bigint;
    allTimeBP: bigint;
}
export interface LessonProgress {
    lessonId: string;
    attempted: boolean;
    completionTime: Time;
    completed: boolean;
    unlocked: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    xp: bigint;
    lessonsCompletedToday: bigint;
    streak: bigint;
    displayName: string;
    lastActivityTime: Time;
    level: bigint;
    lastStreakUpdate: Time;
    avatar: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    attemptQuiz(lessonId: string): Promise<void>;
    changeDisplayName(newName: string): Promise<string>;
    completeLesson(args: CompleteLessonArgs): Promise<{
        bpAwarded: bigint;
        dailyBonusApplied: boolean;
        streakBonusApplied: boolean;
        isFirstCompletion: boolean;
    }>;
    completeOnboarding(displayName: string, avatar: string): Promise<void>;
    completeQuest(args: CompleteQuestArgs): Promise<void>;
    getAllWorld0Lessons(): Promise<Array<[string, string]>>;
    getAnalyticsStats(): Promise<AnalyticsStats>;
    getBearCredits(): Promise<BearCredits | null>;
    getBestQuizScore(lessonId: string): Promise<bigint | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentWorldLessonProgress(worldId: string): Promise<Array<LessonProgress>>;
    getGlobalLeaderboard(): Promise<Array<BPLeaderboardEntry>>;
    getMonthlyLeaderboard(month: bigint, year: bigint): Promise<Array<BPLeaderboardEntry>>;
    getMyDailyStats(): Promise<{
        lessonsToday: bigint;
        streak: bigint;
        firstLessonBonusAvailable: boolean;
    }>;
    getNameChangeCount(): Promise<bigint>;
    getOnboardingStatus(): Promise<[boolean, string, string]>;
    getPersistentUserState(): Promise<[boolean, string, string]>;
    getPublicMetrics(): Promise<{
        activeLearnersToday: bigint;
        mostCompletedLessonWeekly?: string;
        averageProgress: bigint;
    }>;
    getReturnedValue(): Promise<bigint>;
    getUserBearCredits(user: Principal): Promise<BearCredits | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserWorldProgress(user: Principal, worldId: string): Promise<Array<LessonProgress>>;
    getWinnerClaims(): Promise<Array<WinnerClaim>>;
    getWinnerHistory(): Promise<Array<WinnerClaim>>;
    /**
     * / Returns true if the caller has already seen the given share milestone modal.
     */
    hasSeenShareMilestone(milestone: string): Promise<boolean>;
    isAdminUser(): Promise<boolean>;
    /**
     * / Returns true if the caller has ever submitted the boss quiz for the given world.
     * / Boss quizzes are stored in lessonAttempts under the key "boss-<worldId>".
     */
    isBossAttempted(worldId: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isLessonUnlocked(lessonId: string): Promise<boolean>;
    /**
     * / Returns true if the caller has unlocked the given special world.
     */
    isSpecialWorldUnlocked(worldId: string): Promise<boolean>;
    markClaimPaid(month: bigint, year: bigint): Promise<void>;
    markLessonAttempted(lessonId: string): Promise<void>;
    /**
     * / Mark the given share milestone as seen for the caller. Idempotent.
     */
    markShareMilestoneSeen(milestone: string): Promise<void>;
    /**
     * / Mark a special world as unlocked for the caller. Idempotent.
     */
    markSpecialWorldUnlocked(worldId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePersistentUserState(displayName: string, avatar: string, profileComplete: boolean): Promise<void>;
    submitBearPoints(allTimeBP: bigint, monthlyBP: bigint, month: bigint, year: bigint): Promise<void>;
    submitQuiz(args: SubmitQuizArgs): Promise<QuizResult>;
    submitWinnerClaim(month: bigint, year: bigint, usdcAddress: string): Promise<string>;
    trackPageView(): Promise<void>;
    trackProgressEvent(_progress: bigint): Promise<void>;
    /**
     * / Persists caller's current rank snapshot and returns delta vs previous snapshot.
     * / Returns null if no prior snapshot exists (first call).
     * / delta > 0 means rank improved (moved up), delta < 0 means rank dropped.
     */
    updateMyRankSnapshot(currentRank: bigint): Promise<bigint | null>;
    updatePersistentUserState(displayName: string, avatar: string, profileComplete: boolean): Promise<void>;
    updateProfile(args: UpdateProfileArgs): Promise<void>;
}
import type { BearCredits as _BearCredits, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async attemptQuiz(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.attemptQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.attemptQuiz(arg0);
            return result;
        }
    }
    async changeDisplayName(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.changeDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeDisplayName(arg0);
            return result;
        }
    }
    async completeLesson(arg0: CompleteLessonArgs): Promise<{
        bpAwarded: bigint;
        dailyBonusApplied: boolean;
        streakBonusApplied: boolean;
        isFirstCompletion: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.completeLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeLesson(arg0);
            return result;
        }
    }
    async completeOnboarding(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOnboarding(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOnboarding(arg0, arg1);
            return result;
        }
    }
    async completeQuest(arg0: CompleteQuestArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeQuest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeQuest(arg0);
            return result;
        }
    }
    async getAllWorld0Lessons(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorld0Lessons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorld0Lessons();
            return result;
        }
    }
    async getAnalyticsStats(): Promise<AnalyticsStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsStats();
            return result;
        }
    }
    async getBearCredits(): Promise<BearCredits | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBearCredits();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBearCredits();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBestQuizScore(arg0: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBestQuizScore(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBestQuizScore(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentWorldLessonProgress(arg0: string): Promise<Array<LessonProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentWorldLessonProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentWorldLessonProgress(arg0);
            return result;
        }
    }
    async getGlobalLeaderboard(): Promise<Array<BPLeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalLeaderboard();
            return result;
        }
    }
    async getMonthlyLeaderboard(arg0: bigint, arg1: bigint): Promise<Array<BPLeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyLeaderboard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyLeaderboard(arg0, arg1);
            return result;
        }
    }
    async getMyDailyStats(): Promise<{
        lessonsToday: bigint;
        streak: bigint;
        firstLessonBonusAvailable: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDailyStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDailyStats();
            return result;
        }
    }
    async getNameChangeCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNameChangeCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNameChangeCount();
            return result;
        }
    }
    async getOnboardingStatus(): Promise<[boolean, string, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnboardingStatus();
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnboardingStatus();
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async getPersistentUserState(): Promise<[boolean, string, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersistentUserState();
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersistentUserState();
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async getPublicMetrics(): Promise<{
        activeLearnersToday: bigint;
        mostCompletedLessonWeekly?: string;
        averageProgress: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicMetrics();
                return from_candid_record_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicMetrics();
            return from_candid_record_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReturnedValue(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReturnedValue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReturnedValue();
            return result;
        }
    }
    async getUserBearCredits(arg0: Principal): Promise<BearCredits | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBearCredits(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBearCredits(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWorldProgress(arg0: Principal, arg1: string): Promise<Array<LessonProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWorldProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWorldProgress(arg0, arg1);
            return result;
        }
    }
    async getWinnerClaims(): Promise<Array<WinnerClaim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWinnerClaims();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWinnerClaims();
            return result;
        }
    }
    async getWinnerHistory(): Promise<Array<WinnerClaim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWinnerHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWinnerHistory();
            return result;
        }
    }
    async hasSeenShareMilestone(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasSeenShareMilestone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasSeenShareMilestone(arg0);
            return result;
        }
    }
    async isAdminUser(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminUser();
            return result;
        }
    }
    async isBossAttempted(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isBossAttempted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isBossAttempted(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isLessonUnlocked(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isLessonUnlocked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isLessonUnlocked(arg0);
            return result;
        }
    }
    async isSpecialWorldUnlocked(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSpecialWorldUnlocked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSpecialWorldUnlocked(arg0);
            return result;
        }
    }
    async markClaimPaid(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markClaimPaid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markClaimPaid(arg0, arg1);
            return result;
        }
    }
    async markLessonAttempted(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markLessonAttempted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markLessonAttempted(arg0);
            return result;
        }
    }
    async markShareMilestoneSeen(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markShareMilestoneSeen(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markShareMilestoneSeen(arg0);
            return result;
        }
    }
    async markSpecialWorldUnlocked(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSpecialWorldUnlocked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSpecialWorldUnlocked(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async savePersistentUserState(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePersistentUserState(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePersistentUserState(arg0, arg1, arg2);
            return result;
        }
    }
    async submitBearPoints(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBearPoints(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBearPoints(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitQuiz(arg0: SubmitQuizArgs): Promise<QuizResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuiz(arg0);
            return result;
        }
    }
    async submitWinnerClaim(arg0: bigint, arg1: bigint, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWinnerClaim(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWinnerClaim(arg0, arg1, arg2);
            return result;
        }
    }
    async trackPageView(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackPageView();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackPageView();
            return result;
        }
    }
    async trackProgressEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackProgressEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackProgressEvent(arg0);
            return result;
        }
    }
    async updateMyRankSnapshot(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyRankSnapshot(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyRankSnapshot(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePersistentUserState(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePersistentUserState(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePersistentUserState(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProfile(arg0: UpdateProfileArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BearCredits]): BearCredits | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activeLearnersToday: bigint;
    mostCompletedLessonWeekly: [] | [string];
    averageProgress: bigint;
}): {
    activeLearnersToday: bigint;
    mostCompletedLessonWeekly?: string;
    averageProgress: bigint;
} {
    return {
        activeLearnersToday: value.activeLearnersToday,
        mostCompletedLessonWeekly: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.mostCompletedLessonWeekly)),
        averageProgress: value.averageProgress
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
